#!/bin/bash

step () {
    echo -e "\e[1;35m==> $1\e[0m"
}

SCRIPT_DIR=`dirname $0`

#-------------------------------------------------------------------------------
step 'Update'
#-------------------------------------------------------------------------------

sudo pacman -Syu

#-------------------------------------------------------------------------------
step 'Sway'
#-------------------------------------------------------------------------------

sudo pacman -S xorg-server-xwayland mesa pacman-contrib sway swayidle termite grim slurp mako

#-------------------------------------------------------------------------------
step 'Soft'
#-------------------------------------------------------------------------------

sudo pacman -S wget git neofetch ntfs-3g pulseaudio pamixer noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-liberation polkit-gnome nautilus gvfs-mtp file-roller unrar ffmpegthumbnailer gnome-disk-utility gnome-themes-extra gnome-system-monitor shotwell evince chromium transmission-gtk youtube-dl php mpv gedit eog code papirus-icon-theme materia-gtk-theme

#-------------------------------------------------------------------------------
step 'Swap'
#-------------------------------------------------------------------------------

sudo fallocate -l 1G    /swapfile
sudo chmod 600          /swapfile
sudo mkswap             /swapfile
sudo swapon             /swapfile
sudo sh -c 'echo /swapfile none swap defaults 0 0 >> /etc/fstab'

#-------------------------------------------------------------------------------
step 'Config'
#-------------------------------------------------------------------------------

mkdir -p ~/Desktop
mkdir -p ~/Documents
mkdir -p ~/Domains
mkdir -p ~/Downloads
mkdir -p ~/.config

cp      $SCRIPT_DIR/bash/.bashrc            ~/
cp  -rf $SCRIPT_DIR/sway                    ~/.config/
cp  -rf $SCRIPT_DIR/mpv                     ~/.config/
cp  -rf $SCRIPT_DIR/termite                 ~/.config/

sudo chown -R qtm:users                     $SCRIPT_DIR/apps
sudo chmod -R 777                           $SCRIPT_DIR/apps
sudo cp $SCRIPT_DIR/apps/pacinfo            /usr/bin

#-------------------------------------------------------------------------------
step 'Done!'
#-------------------------------------------------------------------------------
