#!/bin/bash

step () {
    echo -e "\e[1;35m==> $1\e[0m"
}

SCRIPT_DIR=`dirname $0`

#-------------------------------------------------------------------------------
step 'Update'
#-------------------------------------------------------------------------------

sudo pacman -Syu

#-------------------------------------------------------------------------------
step 'Sway'
#-------------------------------------------------------------------------------

sudo pacman -S xorg-server-xwayland mesa sway swayidle alacritty dmenu grim slurp mako xdg-user-dirs

#-------------------------------------------------------------------------------
step 'Soft'
#-------------------------------------------------------------------------------

sudo pacman -S wget neofetch ntfs-3g pulseaudio pamixer noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-liberation polkit-gnome nautilus gvfs-mtp file-roller unrar ffmpegthumbnailer gnome-disk-utility gnome-themes-extra gnome-system-monitor shotwell evince firefox transmission-gtk youtube-dl mpv gedit eog arc-icon-theme arc-gtk-theme

#-------------------------------------------------------------------------------
step 'Swap'
#-------------------------------------------------------------------------------

sudo dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
sudo chmod 600          /swapfile
sudo mkswap             /swapfile
sudo swapon             /swapfile
sudo sh -c 'echo /swapfile none swap defaults 0 0 >> /etc/fstab'

#-------------------------------------------------------------------------------
step 'Config'
#-------------------------------------------------------------------------------
xdg-user-dirs-update
mkdir -p ~/.config

cp  -f  $SCRIPT_DIR/bash/.bashrc            ~/
cp  -rf $SCRIPT_DIR/sway                    ~/.config/
cp  -rf $SCRIPT_DIR/mpv                     ~/.config/

sudo chown -R qtm:users                     $SCRIPT_DIR/apps
sudo chmod -R 777                           $SCRIPT_DIR/apps
sudo cp $SCRIPT_DIR/apps/pacinfo            /usr/bin

#-------------------------------------------------------------------------------
step 'Done!'
#-------------------------------------------------------------------------------
